### ISSUE TITLE
Location is not updated with Google services disabled

### ISSUE THREAD

**Issue by Atrate** [Zverik/every_door#199] opened 2022-05-16 05:45 UTC
**Device info:**
OS: DivestOS 19, Android 12
Location services: GPS only, no GNSS/Wifi
App version: 0.3.0 from Google Play

**Problem description:**

After I upgraded my phone from A11 to A12, ED can't seem to get a location lock. Wiping application data makes ED get one lock, but no more than that, no matter how many times the app is restarted.

Everything worked without a problem on Android 11.

Other GPS-using apps work well, such as OSMAnd.

I can provide a logcat capture if that's useful.

**Comment by Zverik** [comment] 2022-05-16 06:35
Possibly related to #106.

**Comment by Atrate** [comment] 2022-05-23 07:48
Does not seem to be fixed in 0.4, from my testing.

**Comment by Zverik** [comment] 2022-05-23 08:17
Thanks Atrate. I guess I'll replace the geolocation library for 0.5.

**Comment by freeExec** [comment] 2022-07-27 16:10
A workaround is to force another application to use GNSS in the background, for example, record a track in Osmand.

**Comment by Zverik** [comment] 2022-08-06 19:30
Must be fixed in 0.9, please check.

**Comment by Zverik** [comment] 2022-08-09 09:30
Looks like this all is an upstream issue:

* https://github.com/Baseflow/flutter-geolocator/issues/1114
* https://github.com/Baseflow/flutter-geolocator/issues/1027
* https://github.com/Baseflow/flutter-geolocator/issues/667

I might have to change the library.

**Comment by Atrate** [comment] 2022-08-14 09:56
> Must be fixed in 0.9, please check.

Not fixed, unfortunately

**Comment by blubearec** [comment] 2022-08-18 16:04
Hi from Ecuador, We're facing the same issue. We are waiting for a fix on this, thanks in advance.

**Comment by Zverik** [comment] 2022-10-03 11:41
Progress report: last weekend I:

1. Confirmed that GPS does not work in the `geolocator_android` library (that I'm using) versions 3.0.4, 3.1.8, 4.0.2. I could not build 2.1.0, but it's too old anyway.
2. Rewrote geolocation to the `location` library version 4.4.0. Raw GPS still does not work, and it seems that version was built around Google services. Will try 5.0.0-dev.8.
3. Tried to find a third geolocation library, failed.

I have a suspicion that there's something wrong with my location flow or library dependencies. Will also try building a minimal app to test these two libraries from the scratch.

**Comment by Atrate** [comment] 2022-10-09 17:53
> Tried to find a third geolocation library, failed.

@Zverik what about using a library that StreetComplete or Vespucci or OSMand use? They work fine without Google.

**Comment by Zverik** [comment] 2022-10-11 08:04
I would love to use their solutions, but all of these are native Android apps, while Every Door was written in Dart / Flutter. But maybe I could use something in the android part of the geolocation library.

**Comment by Zverik** [comment] 2022-10-16 19:56
Okay, I give up for now. This requires a lot of in-depth knowledge of Android geolocation programming. I welcome any help with [this source code](https://github.com/Baseflow/flutter-geolocator/tree/main/geolocator_android/android/src/main/java/com/baseflow/geolocator/location).

For a bypass, I'm doing #281 with an option for zooming out up to zoom 4.

**Comment by mahdi1234** [comment] 2022-10-23 12:58
That's pity, I really like the app after trying it for the first time today, but have to kill it all the time to get new location. LOS 19.1 without any gapps.

**Comment by Zverik** [comment] 2022-10-23 13:30
If anybody finds a Flutter-based app with geolocation that works without Google services, I could use that as well. To me it seems like every location library is broken. On the positive side, it concerns only Android 12+.

**Comment by mahdi1234** [comment] 2022-10-24 10:08
Hi Ilya I have briefly discussed this in small matrix community and they had some ideas about code, if you'd like to join you're all welcomed at https://matrix.to/#/#flutter-devs:matrix.org

disclaimer: I myself am not a dev, just user.

**Comment by Atrate** [comment] 2023-07-22 10:47
I think installing https://github.com/microg/FakeStore fixed the issue for some reason? I do not have microg installed, though, so it's quite weird, maybe an Android update fixed it instead?

**Comment by Zverik** [comment] 2023-10-02 15:04
Looks like it was fixed!

**Closed by Zverik** 2023-10-02 15:04 UTC
Labels: bug, help wanted, meta
