### ISSUE TITLE
OAuth login silently fails

### ISSUE THREAD

**Issue by Self-Perfection** [Zverik/every_door#219] opened 2022-05-22 13:18 UTC
I get similar behaviour with version 0.3 from google play and 0.4 from releases.

Tapping "Login with OAuth" brings up webview with OSM website and permissions request. I tap "Authorize", webview disappears, but nothing and I'm back to map, but the app has not actually authorized. I've attempted record logs and this might be relevant:

```
05-22 17:07:54.641 32321 32321 I ilya.every_doo: Rejecting re-init on previously-failed class java.lang.Class<androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/window/sidecar/SidecarInterface$SidecarCallback;
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.ExtensionInterfaceCompat androidx.window.layout.SidecarWindowBackend$Companion.initAndVerifyExtension(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.SidecarWindowBackend androidx.window.layout.SidecarWindowBackend$Companion.getInstance(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowBackend androidx.window.layout.WindowInfoTracker$Companion.windowBackend$window_release(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowInfoTracker androidx.window.layout.WindowInfoTracker$Companion.getOrCreate(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at io.flutter.embedding.android.s io.flutter.embedding.android.j.n() (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void io.flutter.embedding.android.j.onAttachedToWindow() (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.View.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (View.java:18359)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3397)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.642 32321 32321 I chatty  : uid=10251(info.zverev.ilya.every_door) identical 1 line
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:1770)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:1468)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:7208)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:1004)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doCallbacks(int, long) (Choreographer.java:816)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doFrame(long, int) (Choreographer.java:751)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:990)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.os.Looper.loop() (Looper.java:193)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6762)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
05-22 17:07:54.642 32321 32321 I ilya.every_doo: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.window.sidecar.SidecarInterface$SidecarCallback" on path: DexPathList[[zip file "/data/app/info.zverev.ilya.every_door-zY-Uh0sYsaxl1BWpsDOKrg==/base.apk"],nativeLibraryDirectories=[/data/app/info.zverev.ilya.every_door-zY-Uh0sYsaxl1BWpsDOKrg==/lib/arm64, /data/app/info.zverev.ilya.every_door-zY-Uh0sYsaxl1BWpsDOKrg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.ExtensionInterfaceCompat androidx.window.layout.SidecarWindowBackend$Companion.initAndVerifyExtension(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.SidecarWindowBackend androidx.window.layout.SidecarWindowBackend$Companion.getInstance(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowBackend androidx.window.layout.WindowInfoTracker$Companion.windowBackend$window_release(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowInfoTracker androidx.window.layout.WindowInfoTracker$Companion.getOrCreate(android.content.Context) (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at io.flutter.embedding.android.s io.flutter.embedding.android.j.n() (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void io.flutter.embedding.android.j.onAttachedToWindow() (:-1)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.View.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (View.java:18359)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3397)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.642 32321 32321 I chatty  : uid=10251(info.zverev.ilya.every_door) identical 1 line
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:1770)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:1468)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:7208)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:1004)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doCallbacks(int, long) (Choreographer.java:816)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doFrame(long, int) (Choreographer.java:751)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:990)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
05-22 17:07:54.642 32321 32321 I ilya.every_doo:   at void android.os.Looper.loop() (Looper.java:193)
05-22 17:07:54.643 32321 32321 I ilya.every_doo:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6762)
05-22 17:07:54.643 32321 32321 I ilya.every_doo:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
05-22 17:07:54.643 32321 32321 I ilya.every_doo:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
05-22 17:07:54.643 32321 32321 I ilya.every_doo:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
05-22 17:07:54.643 32321 32321 I ilya.every_doo: 
05-22 17:07:54.643 32321 32321 I ilya.every_doo: Rejecting re-init on previously-failed class java.lang.Class<androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/window/sidecar/SidecarInterface$SidecarCallback;
05-22 17:07:54.643 32321 32321 I ilya.every_doo:   at androidx.window.layout.ExtensionInterfaceCompat androidx.window.layout.SidecarWindowBackend$Companion.initAndVerifyExtension(android.content.Context) (:-1)
05-22 17:07:54.643 32321 32321 I ilya.every_doo:   at androidx.window.layout.SidecarWindowBackend androidx.window.layout.SidecarWindowBackend$Companion.getInstance(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowBackend androidx.window.layout.WindowInfoTracker$Companion.windowBackend$window_release(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowInfoTracker androidx.window.layout.WindowInfoTracker$Companion.getOrCreate(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at io.flutter.embedding.android.s io.flutter.embedding.android.j.n() (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void io.flutter.embedding.android.j.onAttachedToWindow() (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.View.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (View.java:18359)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3397)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.644 32321 32321 I chatty  : uid=10251(info.zverev.ilya.every_door) identical 1 line
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:1770)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:1468)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:7208)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:1004)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doCallbacks(int, long) (Choreographer.java:816)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doFrame(long, int) (Choreographer.java:751)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:990)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.os.Looper.loop() (Looper.java:193)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6762)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
05-22 17:07:54.644 32321 32321 I ilya.every_doo: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.window.sidecar.SidecarInterface$SidecarCallback" on path: DexPathList[[zip file "/data/app/info.zverev.ilya.every_door-zY-Uh0sYsaxl1BWpsDOKrg==/base.apk"],nativeLibraryDirectories=[/data/app/info.zverev.ilya.every_door-zY-Uh0sYsaxl1BWpsDOKrg==/lib/arm64, /data/app/info.zverev.ilya.every_door-zY-Uh0sYsaxl1BWpsDOKrg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at androidx.window.layout.ExtensionInterfaceCompat androidx.window.layout.SidecarWindowBackend$Companion.initAndVerifyExtension(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at androidx.window.layout.SidecarWindowBackend androidx.window.layout.SidecarWindowBackend$Companion.getInstance(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowBackend androidx.window.layout.WindowInfoTracker$Companion.windowBackend$window_release(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at androidx.window.layout.WindowInfoTracker androidx.window.layout.WindowInfoTracker$Companion.getOrCreate(android.content.Context) (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at io.flutter.embedding.android.s io.flutter.embedding.android.j.n() (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void io.flutter.embedding.android.j.onAttachedToWindow() (:-1)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.View.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (View.java:18359)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3397)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.644 32321 32321 I chatty  : uid=10251(info.zverev.ilya.every_door) identical 1 line
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewGroup.dispatchAttachedToWindow(android.view.View$AttachInfo, int) (ViewGroup.java:3404)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:1770)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:1468)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:7208)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:1004)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doCallbacks(int, long) (Choreographer.java:816)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer.doFrame(long, int) (Choreographer.java:751)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:990)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.os.Looper.loop() (Looper.java:193)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6762)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
05-22 17:07:54.644 32321 32321 I ilya.every_doo:
```
Device is Xiaomi Mi A1, Android 9.

**Comment by Zverik** [comment] 2022-08-01 11:59
Alas I cannot reproduce this. Closing until we get more of these.

**Closed by Zverik** 2022-08-01 11:59 UTC
