### ISSUE TITLE
Moving the cursor in the text field highlights a part of the text

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#302] opened 2022-07-07 20:32 UTC
https://user-images.githubusercontent.com/25708359/177866179-88799e2c-644a-4082-bcad-b07e092d89ad.mp4

Samsung Galaxy A52, Android 12, OneUI 4.1

**Comment by Zverik** [comment] 2022-07-08 06:54
Alas I cannot reproduce it on Xperia X Compact with SwiftKey. Anybody else?

**Comment by deevroman** [comment] 2022-07-08 20:28
Also does not reproduce on Realme c11 Android 11 and Samsung J1 Android 5.1.1

**Comment by Zverik** [comment] 2022-08-29 12:41
Closing this for now. Do open if you find a way to reproduce.

**Closed** 2022-08-29 12:45 UTC

**Comment by deevroman** [comment] 2022-08-29 14:58
it looks like this is a Samsung Keyboard problem in all applications on Flutter. This does not happen with Yandex.Keyboard. I sent an error report to Samsung, but apparently it is impossible to observe it publicly.
