### ISSUE TITLE
Add support for images on Notes

### ISSUE THREAD

**Issue by coolultra1** [Zverik/every_door#623] opened 2023-08-18 11:13 UTC
When creating notes on the go, you often times want to add an image to the note. StreetComplete has a solution for that, having an image server that the app uploads the image and then links the images there in the note.

Maybe, if we asked nicely, they'd allow EveryDoor to use their image server as well?

**Comment by deevroman** [comment] 2023-08-18 17:14
Duplicate of https://github.com/Zverik/every_door/issues/184

**Closed** 2024-04-01 07:49 UTC
