### ISSUE TITLE
Pending uploads list versus "does not exist" button 

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#420] opened 2022-09-02 00:43 UTC
Go to pending uploads. Touch an item, and in that item press the "does not exist" button and confirm.
The item should disappear from the pending uploads list instantly. But it doesn't.
We have to go back out of and back into the list to make  the display update.

**Comment by GeorgeHoneywood** [comment] 2022-09-02 07:04
This has already been fixed, and will be released in the [2.0 version](https://github.com/Zverik/every_door/blob/main/CHANGELOG.md).

**Comment by Zverik** [comment] 2022-09-02 08:55
Yup, duplicate of #381.

**Closed by Zverik** 2022-09-02 08:55 UTC
