### ISSUE TITLE
GPS polling interval is very long

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#165] opened 2022-05-11 19:02 UTC
I think this is an amazing app. Micromapping mode fills a hole that I've been bothered by for awhile.

One use of apps like this for me is to stand at or near an object and then add the point on or near the location indicator. When it's in 'follow location' mode, the new point is automatically added right where you are, which is great! However, I noticed that it seems to take about 10 seconds for location to update. I can understand that this might be for battery saving purposes, but it's hard to tell whether I'm in the right place sometimes. Could this interval be shortened? One second might be too much, but maybe 3 seconds?

**Comment by Zverik** [comment] 2022-05-11 19:04
Thanks, pkoby! I'll look into it, no idea why this is the case for now.

Closing as a duplicate of #106.

**Closed by Zverik** 2022-05-11 19:04 UTC

**Comment by pkoby** [comment] 2022-05-11 19:05
Whoops, didn't search for the right terms... Thanks!
