### ISSUE TITLE
Please act as share target

### ISSUE THREAD

**Issue by jech** [Zverik/every_door#769] opened 2024-08-17 17:57 UTC
Hi,

I was expecting to be able to share a location from my maps application in order to open Every Door at the right place.  Unfortunately, Every Door does not appear in the share menu.

Tried both with Organic Maps (which has its own, idiosyncratic share format) and using a `geo:` link from osm2gmaps.

Please act as a share target, at least for `geo:` links (RFC 5870).

**Comment by deevroman** [comment] 2024-08-17 18:04
Duplicate of http://github.com/Zverik/every_door/issues/387

**Closed** 2024-09-21 17:34 UTC
