### ISSUE TITLE
don’t add “Please merge me into a nearby building” to memorial plaques, ask how it is attached

### ISSUE THREAD

**Issue by skfd** [Zverik/every_door#735] opened 2024-05-20 04:37 UTC
Memorial Plaques can be on a pole, free standing. You add fixme tag that I can not even edit when I add Memorial Plaque template, it opaquely appears after.

**Comment by Zverik** [comment] 2024-05-22 07:24
Duplicate of #565, please track the issue there.

**Closed by Zverik** 2024-05-22 07:24 UTC
